#!/bin/bash

EXEC=""
TARGET="buildScript"
ORIG_ARGS="$*"
declare -a PARAMS
declare -i INDEX=0

for e in "$@"; do
  TARGET="$TARGET/$e"
  PARAMS[$INDEX]="$e"
  INDEX=$INDEX+1
  shift
  if [ -x "${TARGET}.sh" ]; then
    EXEC="${TARGET}.sh"
    PARAMS=()
    INDEX=0
  fi
done

if [ -z "$EXEC" ]; then
  echo "no matching build script for: $ORIG_ARGS" >&2
  exit 1
fi

echo ">> $EXEC"
exec "$EXEC" "${PARAMS[@]}"
