name: Preview Build
on:
  workflow_dispatch:
jobs:
  libcore:
    uses: ./.github/workflows/libcore.yml
  build:
    needs: libcore
    uses: ./.github/workflows/build-apk.yml
    with:
      gradle-task: app:assemblePreviewRelease
    secrets: inherit
