name: Release Build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: true
      publish:
        description: "Publish: If want ignore"
        required: false
jobs:
  libcore:
    uses: ./.github/workflows/libcore.yml
    with:
      ref: ${{ inputs.tag }}
  build:
    needs: libcore
    uses: ./.github/workflows/build-apk.yml
    with:
      gradle-task: app:assembleOssRelease
      ref: ${{ inputs.tag }}
    secrets: inherit
  publish:
    name: Publish Release
    if: github.event.inputs.publish != 'y'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ inputs.tag }}
      - name: Donwload Artifacts
        uses: actions/download-artifact@v4
        with:
          name: APKs
          path: artifacts
      - name: Release
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          echo "c428627270ae26e206cb526cb8c7bdfba475dd278f6691ddaf863355adadfa13  ghr.tar.gz" | sha256sum -c -
          tar -xvf ghr.tar.gz
          mv ghr*linux_amd64/ghr .
          mkdir apks
          find artifacts -name "*.apk" -exec cp {} apks \;
          ./ghr -delete -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" apks
